version: "3.8"
services:
  gabguy-gui:
    image: gabguy:latest
    build:
      context: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    command: ["bash", "-c", "cd /src && java Main"]
    profiles:
      - donotstart

  gabguy-cli:
    image: gabguy:latest
    build:
      context: .
    command: ["bash", "-c", "cd /src && java Main cli"]
    profiles:
    - donotstart
